const students = [
	{ id: 2, name: "Alpaca", image: "assets/images/students/alpaca.jpg" },
	{ id: 3, name: "Bison", image: "assets/images/students/bison.jpg" },
	{ id: 4, name: "Buffalo", image: "assets/images/students/buffalo.jpg" },
	{ id: 6, name: "Bunny", image: "assets/images/students/bunny.jpg" },
	{ id: 7, name: "Capybara", image: "assets/images/students/capybara.jpg" },
	{ id: 8, name: "Cat", image: "assets/images/students/cat.jpg" },
	{ id: 9, name: "Cheetah", image: "assets/images/students/cheetah.jpg" },
	{ id: 10, name: "Chick", image: "assets/images/students/chick.jpg" },
	{ id: 11, name: "Cow", image: "assets/images/students/cow.jpg" },
	{ id: 12, name: "Dog", image: "assets/images/students/dog.jpg" },
	{ id: 13, name: "Dolphin", image: "assets/images/students/dolphin.jpg" },
	{ id: 14, name: "Donkey", image: "assets/images/students/donkey.jpg" },
	{ id: 15, name: "Duck", image: "assets/images/students/duck.jpg" },
	{ id: 16, name: "Duckling", image: "assets/images/students/duckling.jpg" },
	{ id: 17, name: "Frontend Developer", image: "assets/images/students/frontend_developer.jpg" },
	{ id: 18, name: "Guinea pig", image: "assets/images/students/guniea_pig.jpg" },
	{ id: 20, name: "Hedgehog", image: "assets/images/students/hedgehog.jpg" },
	{ id: 21, name: "Hippo", image: "assets/images/students/hippo.jpg" },
	{ id: 22, name: "Horse", image: "assets/images/students/horse.jpg" },
	{ id: 25, name: "Meerkat", image: "assets/images/students/meerkat.jpg" },
	{ id: 26, name: "Monkey", image: "assets/images/students/monkey.jpg" },
	{ id: 27, name: "Ostrich", image: "assets/images/students/ostrich.jpg" },
	{ id: 28, name: "Owl", image: "assets/images/students/owl.jpg" },
	{ id: 29, name: "Panda", image: "assets/images/students/panda.jpg" },
	{ id: 30, name: "Parrot", image: "assets/images/students/parrot.jpg" },
	{ id: 31, name: "Peacock", image: "assets/images/students/peacock.jpg" },
	{ id: 32, name: "Penguin", image: "assets/images/students/penguin.jpg" },
	{ id: 33, name: "Pig", image: "assets/images/students/pig.jpg" },
	{ id: 34, name: "Rhino", image: "assets/images/students/rhino.jpg" },
	{ id: 35, name: "Rooster", image: "assets/images/students/rooster.jpg" },
	{ id: 37, name: "Sheep", image: "assets/images/students/sheep.jpg" },
	{ id: 38, name: "Snail", image: "assets/images/students/snail.jpg" },
	{ id: 39, name: "Squirrel", image: "assets/images/students/squirrel.jpg" },
	{ id: 40, name: "Tiger", image: "assets/images/students/tiger.jpg" },
	{ id: 41, name: "Turtle", image: "assets/images/students/turtle.jpg" },
	{ id: 42, name: "Wolf", image: "assets/images/students/wolf.jpg" },
	{ id: 45, name: "Zebra", image: "assets/images/students/zebra" },
	{ id: 43, name: "Frog", image: "assets/images/students/frog.jpg" },
	{ id: 44, name: "Swan", image: "assets/images/students/swan.jpg" },
	{ id: 47, name: "Koala", image: "assets/images/students/koala.jpg" },
	{ id: 48, name: "Pigeon", image: "assets/images/students/pigeon.jpg" },
];

const missing_students = [
	{ id: 1, name: "Adam", image: "assets/images/students/adam.jpg" },
	{ id: 5, name: "Amin", image: "assets/images/students/amin.jpg" },
	{ id: 19, name: "Erik T.", image: "assets/images/students/erik.jpg" },
	{ id: 22, name: "Jacob", image: "assets/images/students/jacob.jpg" },
	{ id: 23, name: "Joakim", image: "assets/images/students/joakim.jpg" },
	{ id: 36, name: "Nichlas", image: "assets/images/students/nichlas.jpg" },
	{ id: 46, name: "Torbjörn", image: "assets/images/students/torbjorn.jpg" },
];
